/**
 * Patient REST API
 * This is a REST API of Patient REST API, where you can get/add/remove/modify Patient board and its visit.
 *
 * OpenAPI spec version: v1
 * Contact: michele.antonacci1098@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs';
import {Visit} from '../model/visit';
import {VisitDTO} from '../model/visitDTO';
import {Configuration} from "./configuration";
import {BASE_PATH} from "./variables";


@Injectable()
export class VisitControllerService {

  protected basePath = 'http://localhost:8080/api';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }


  /**
   * Save new visit
   *
   * @param visitDTO visitDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createVisitUsingPOST(visitDTO: VisitDTO, observe?: 'body', reportProgress?: boolean): Observable<Visit>;
  public createVisitUsingPOST(visitDTO: VisitDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Visit>>;
  public createVisitUsingPOST(visitDTO: VisitDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Visit>>;
  public createVisitUsingPOST(visitDTO: VisitDTO, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (visitDTO === null || visitDTO === undefined) {
      throw new Error('Required parameter visitDTO was null or undefined when calling createVisitUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<Visit>(`${this.basePath}/visits/`,
      visitDTO,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Delete Visit with specific id
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteVisitUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<string>;
  public deleteVisitUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
  public deleteVisitUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
  public deleteVisitUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deleteVisitUsingDELETE.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete<string>(`${this.basePath}/visits/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
        // @ts-ignore
        responseType: 'text'
      }
    );
  }

  /**
   * View a list of all visits
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllVisitsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Visit>>;
  public getAllVisitsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Visit>>>;
  public getAllVisitsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Visit>>>;
  public getAllVisitsUsingGET(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<Array<Visit>>(`${this.basePath}/visits/`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Find a visit info by its id
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getVisitUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<Visit>;
  public getVisitUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Visit>>;
  public getVisitUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Visit>>;
  public getVisitUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getVisitUsingGET.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<Visit>(`${this.basePath}/visits/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Update a visit with specific id
   *
   * @param id id
   * @param visitDTO visitDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateVisitUsingPUT(id: number, visitDTO: VisitDTO, observe?: 'body', reportProgress?: boolean): Observable<Visit>;
  public updateVisitUsingPUT(id: number, visitDTO: VisitDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Visit>>;
  public updateVisitUsingPUT(id: number, visitDTO: VisitDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Visit>>;
  public updateVisitUsingPUT(id: number, visitDTO: VisitDTO, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateVisitUsingPUT.');
    }

    if (visitDTO === null || visitDTO === undefined) {
      throw new Error('Required parameter visitDTO was null or undefined when calling updateVisitUsingPUT.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.put<Visit>(`${this.basePath}/visits/${encodeURIComponent(String(id))}`,
      visitDTO,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

}
